name: cw6
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  desktop_window: ^0.4.0
  collection: ^1.19.0
  material_color_utilities: ^0.12.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  lints: ^5.1.0
  stack_trace: ^1.12.0
  string_scanner: ^1.3.0
  test_api: ^0.7.3
  vm_service: ^14.3.0

flutter:
  uses-material-design: true